version: '2'

services:
  app:
    build: "."
    ports:
      - "8000:8000"
    volumes:
      - ./app/:/opt/ChosensyaMaker/app
      - ./public/:/opt/ChosensyaMaker/public
      - ./resources/:/opt/ChosensyaMaker/resources
